egeerardyn/awesome-LaTeX

- README.md
This pull request adds the following two items to the list (in separate commits):
- Texpad: a commercial LaTeX editor for OS X & iOS. By far the best LaTeX editor I've used.
- PetarV-/TikZ: a complete repository of TikZ figures that I have created in (mostly scientific or educational) publications. I plan to continuously update it with new figures as new publications are released. Here is a selection of the (in my opinion) best 10 figures currently in there (alphabetical order):
- [CRT rendering](https://github.com/PetarV-/TikZ/tree/master/CRT%20rendering)
- [de Bruijn graph](https://github.com/PetarV-/TikZ/tree/master/de%20Bruijn%20graph)
- [GameBoy tiling system](https://github.com/PetarV-/TikZ/tree/master/GameBoy%20tiling%20system)
- [git …
> Include Texpad and PetarV-/TikZ

- README.md
I find the visual FAQ very interesting and easy to follow. I placed it near the cookbooks as the aim is somehow similar.
> Add Visual FAQ

- README.md
Follow up to https://github.com/egeerardyn/awesome-LaTeX/pull/13
Although the list of popular editors should also contain online editors, the other list focuses on full text editor only, where as this list also covers other editors such as equation and table.
> Add list of popular online editors

- README.md
I have added the program papis to the bibliography tools.
It is a real alternative to zotero or mendeley.
Warning: I am the main developer.
> Add papis to bibliography tools

- README.md
This adds a link to https://tex.stackexchange.com/q/1319/9075, which is a collection of beautiful typeset documents.
Currently, the first entry displays as follows:
> Add showcase of beautiful typography done in TeX & friends

- README.md
Add https://github.com/lervag/vimtex
> Add vimtex

- README.md
Add https://www.andy-roberts.net/writing/latex
> Add Getting to Grips with LaTeX

- README.md
[TEX TALK](http://tex-talk.net) - Blog for the TeX Stack Exchange site with news and interviews.
> Add TEX TALK

- README.md
To bring this list forward to be included in the [awesome lists](https://github.com/sindresorhus/awesome), I addressed three things of https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md:
- Drop all the A / An prefixes in the descriptions.
- Includes a project logo/illustration whenever possible. 
- Includes the Awesome badge: Should be placed on the right side of the readme heading.
> Drop "A/An" prefixes and add logo

- README.md
Added a bunch of tools. Fixes #34.
> matlab2tikz and more

- README.md
See https://github.com/tectonic-typesetting/tectonic#tectonic for more
details.
> add tectonic engine

- README.md
Add https://learnlatex.github.io/
> Add learning latex

- README.md
Add the game [TeXnique](https://texnique.xyz) to "Resources." Not sure if that's the best section?
> Add TeXnique

- README.md
It is similar to Jekyll and Hugo, but has the LaTeX support from the get-go.
> Add Franklin.jl

- README.md
This online book / tutorial has helped me to understand how to manage my TeX distribution TeXLive correctly. Earlier versions of the book can be found around CTAN and various mirrors. But this is the official current version, and the HTML5 up design makes it a joy to use.
> Add Books > Formatting Information

- README.md
MikTeX is also available for Mac, Linux and as Docker image as #39 also mentioned (and [open source](https://github.com/MiKTeX/miktex)) 🙂
> Change details to MikTeX

- README.md
I think, Docker images are worth mentioning. I was unsure whether I should put them as sub item in the distribution list or keep it as main heading (as done in the PR).
> Add list of awesome Docker Images

- README.md
TopAnswers TeX is a free and open source Q&A site for TeX and friends. It focuses on the needs of the community and has a seamless integration of chat into the Q&A system which makes it well suited for the community to solve even difficult questions.
Disclosure: I'm a user of the site
> Adding TopAnswers TeX

- README.md
This follows https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge and thus prepares to use https://github.com/sindresorhus/awesome-lint.
> Fix awesome logo

- README.md
Add [LaTeX OCR](https://lukas-blecher.github.io/LaTeX-OCR/):
Also add [LTeX](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex).
Since the list was long and there are more than 5 elements in a group, I added sub sections:
- Quality Check Tools
- Tools centered around equations
> Add pix2tex AKA LaTeX OCR - and add separate section on LaTeX equation tooling

- README.md
Add [WebLaTeX](https://github.com/sanjib-sen/weblatex)
> Add weblatex

- README.md
Disclaimer: I am the author of the TeXtured Template.
I believe the [TeXtured](https://github.com/jdujava/TeXtured) Template is really unique and pleasing in its look (this belief was reinforced by large amount of positive reactions). Additionaly, due to its clean coding (structured organization and modern LaTeX packages), it is easy to just copy relevant parts of the code into other projects.
> Add TeXtured to Templates
